### ISSUE TITLE
Add spacing around links and bold elements

### ISSUE THREAD

**Issue by wilzbach** [storyscript/docs.storyscript.io#74]
![image](https://user-images.githubusercontent.com/4370550/58168046-9d221400-7c8d-11e9-9871-7add0be2f637.png)

This is from https://docs.storyscript.io/cli, but interestingly enough I can only observe this locally on master. I am based on https://github.com/storyscript/docs.storyscript.io/commit/086c16b6cc1286664aacf6cc91cb8d7876e3893d with all caches cleared, so maybe it's an issue with the local setup?

**Comment by JeanBarriere** [comment]
Issue with the local setup, as npm is not updating to the proper patch, can't understand why.
Will be fixed locally as well once the theme splitting is done
